# Generated by Django 3.2.5 on 2021-08-08 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_recognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmbedder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='face_detector', max_length=30)),
                ('face_detection_model', models.FileField(upload_to='ai_embedder/')),
                ('caffee_model', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='AIEmbeddings',
            new_name='Embedding',
        ),
        migrations.RenameModel(
            old_name='HistoricalAIEmbeddings',
            new_name='HistoricalEmbedding',
        ),
        migrations.RenameModel(
            old_name='HistoricalAILabel',
            new_name='HistoricalLabel',
        ),
        migrations.RenameModel(
            old_name='HistoricalAIRecognizer',
            new_name='HistoricalRecognizer',
        ),
        migrations.RenameModel(
            old_name='AILabel',
            new_name='Label',
        ),
        migrations.RenameModel(
            old_name='AIRecognizer',
            new_name='Recognizer',
        ),
        migrations.AlterModelOptions(
            name='historicalembedding',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical embedding'},
        ),
        migrations.AlterModelOptions(
            name='historicallabel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical label'},
        ),
        migrations.AlterModelOptions(
            name='historicalrecognizer',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical recognizer'},
        ),
        migrations.CreateModel(
            name='HistoricalAIEmbedder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='face_detector', max_length=30)),
                ('face_detection_model', models.TextField(max_length=100)),
                ('caffee_model', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ai embedder',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
