# Generated by Django 3.2.5 on 2021-07-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
