# Generated by Django 3.2.5 on 2021-08-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0002_auto_20210807_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiembedder',
            name='name',
            field=models.CharField(default='embedder', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalaiembedder',
            name='name',
            field=models.CharField(default='embedder', max_length=30),
        ),
    ]
