# Generated by Django 3.2.5 on 2021-07-25 23:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_recognition', '0003_auto_20210725_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AILabels',
            new_name='AILabel',
        ),
        migrations.RenameModel(
            old_name='HistoricalAILabels',
            new_name='HistoricalAILabel',
        ),
        migrations.AlterModelOptions(
            name='historicalailabel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ai label'},
        ),
    ]
