# Generated by Django 3.2.5 on 2021-08-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0004_auto_20210807_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiembedder',
            old_name='face_detection_model',
            new_name='embedder',
        ),
        migrations.RenameField(
            model_name='historicalaiembedder',
            old_name='face_detection_model',
            new_name='embedder',
        ),
    ]
