# Generated by Django 3.2.5 on 2021-07-25 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_recognition', '0004_auto_20210725_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPhoto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('photo', models.TextField(max_length=100)),
                ('bloob', models.JSONField(default=dict)),
                ('mask', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='face_recognition.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical photo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='employee_photo/% Y/% m/% d/')),
                ('bloob', models.JSONField(default=dict)),
                ('mask', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_recognition.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='photos',
            name='employee',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='name',
            field=models.CharField(default='my_model', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalaimodel',
            name='name',
            field=models.CharField(default='my_model', max_length=30),
        ),
        migrations.AlterField(
            model_name='ailabel',
            name='name',
            field=models.CharField(default='labels', max_length=30),
        ),
        migrations.AlterField(
            model_name='airecognizer',
            name='name',
            field=models.CharField(default='recognizer', max_length=30),
        ),
        migrations.AlterField(
            model_name='airecognizer',
            name='recognizer',
            field=models.FileField(upload_to='ai_recognizer/'),
        ),
        migrations.AlterField(
            model_name='historicalailabel',
            name='name',
            field=models.CharField(default='labels', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalairecognizer',
            name='name',
            field=models.CharField(default='recognizer', max_length=30),
        ),
        migrations.DeleteModel(
            name='HistoricalPhotos',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
