# Generated by Django 3.2.5 on 2021-08-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0005_auto_20210807_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Embedding',
        ),
        migrations.RemoveField(
            model_name='historicalembedding',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallabel',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrecognizer',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Recognizer',
        ),
        migrations.AlterField(
            model_name='bloob',
            name='bloob',
            field=models.CharField(default='0', max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalbloob',
            name='bloob',
            field=models.CharField(default='0', max_length=5000),
        ),
        migrations.DeleteModel(
            name='HistoricalEmbedding',
        ),
        migrations.DeleteModel(
            name='HistoricalLabel',
        ),
        migrations.DeleteModel(
            name='HistoricalRecognizer',
        ),
    ]
