# Generated by Django 3.2.5 on 2021-07-28 16:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_recognition', '0007_auto_20210728_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AIFaceDetector',
            new_name='AIDetector',
        ),
        migrations.RenameModel(
            old_name='HistoricalAIFaceDetector',
            new_name='HistoricalAIDetector',
        ),
        migrations.AlterModelOptions(
            name='historicalaidetector',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ai detector'},
        ),
    ]
