# Generated by Django 3.2.5 on 2021-07-29 12:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_recognition', '0008_auto_20210728_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='EmployeePhoto',
        ),
        migrations.RenameModel(
            old_name='HistoricalPhoto',
            new_name='HistoricalEmployeePhoto',
        ),
        migrations.AlterModelOptions(
            name='historicalemployeephoto',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical employee photo'},
        ),
    ]
