# Generated by Django 3.2.5 on 2021-08-03 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_recognition', '0009_auto_20210729_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeePhoto',
            new_name='EmployeeFacePhoto',
        ),
        migrations.RenameModel(
            old_name='HistoricalEmployeePhoto',
            new_name='HistoricalEmployeeFacePhoto',
        ),
        migrations.AlterModelOptions(
            name='historicalemployeefacephoto',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical employee face photo'},
        ),
        migrations.AddField(
            model_name='employee',
            name='video',
            field=models.FileField(default=None, upload_to='employee_video/'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='video',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeFaceVideo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('video', models.TextField(max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='face_recognition.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee face video',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmployeeFaceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='employee_video/')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_recognition.employee')),
            ],
        ),
    ]
