# Generated by Django 3.2.5 on 2021-08-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0010_auto_20210803_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='video',
            field=models.FileField(upload_to='employee_video/'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='video',
            field=models.TextField(max_length=100),
        ),
    ]
