# Generated by Django 3.2.5 on 2021-08-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0011_auto_20210803_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalemployeefacevideo',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='historicalemployeefacevideo',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='EmployeeFaceVideo',
        ),
        migrations.DeleteModel(
            name='HistoricalEmployeeFaceVideo',
        ),
    ]
