# Generated by Django 3.2.5 on 2021-08-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0012_auto_20210803_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefacephoto',
            name='photo',
            field=models.ImageField(upload_to='employee_photo/'),
        ),
    ]
